### ISSUE TITLE
Download pre-trained GLIP-T and GLIP-L

### ISSUE THREAD

**Issue by WTZ6666** [zyong812/VS3_CVPR23#2]
Hello, when I execute "wget https://penzhanwu2bbs.blob.core.windows.net/data/GLIPv1_Open/models/glip_tiny_model_o365_goldg_cc_sbu.pth -O swin_tiny_patch4_window7_224.pth
", I get this problem, do you know how to fix it?
![image](https://github.com/zyong812/VS3_CVPR23/assets/88275967/5bf7d74c-4093-4b71-b737-acf225092159)

**Comment by zyong812** [comment]
GLIP has updated the downloading paths, please find these checkpoints following https://github.com/microsoft/GLIP#model-zoo
