### ISSUE TITLE
multi-gpu bug

### ISSUE THREAD

**Issue by ZHUXUHAN** [zyong812/VS3_CVPR23#7]
when i use 8 gpus, loss will meet nan , and the training will be stopped, how can i solve it?

**Comment by Clouc-Catkin** [comment]
> when i use 8 gpus, loss will meet nan , and the training will be stopped, how can i solve it?

Hello, I have same problem, my config is 4 GPUs and total batch_size is 4*4=16. Base LR is 8e-4 (8 x original lr) and Lang LR is 8e-5. Error of NaN encountered after 5000 Iters. Could you tell me how to fix this bug? Thanks!

**Comment by Clouc-Catkin** [comment]
> > when i use 8 gpus, loss will meet nan , and the training will be stopped, how can i solve it?
> 
> Hello, I have same problem, my config is 4 GPUs and total batch_size is 4*4=16. Base LR is 8e-4 (8 x original lr) and Lang LR is 8e-5. Error of NaN encountered after 5000 Iters. Could you tell me how to fix this bug? Thanks!

It's solved. 8x LR is too high for 16x Batchsize (4 GPUs, 4 samples per batch for one GPU). I set LR to 2x then NaN errors disappear.
