### ISSUE TITLE
About "DATASETS:   TRAIN: ('vg150_train',)   TEST: ('vg150_test',)"

### ISSUE THREAD

**Issue by ChchunY** [zyong812/VS3_CVPR23#9]
where to find 'vg150_train' and 'vg150_test'?

**Comment by wangjanice8** [comment]
> where to find 'vg150_train' and 'vg150_test'?

Hello,

Did you manage to resolve your issue? Also, could you please let me know where I can download 'vg150_train' and 'vg150_test'?

Thank you.
